"""
Django settings for taskite project.

Generated by 'django-admin startproject' using Django 5.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
import re
import environ
from pathlib import Path

from taskite.settings.django_environ import env

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent

from taskite.settings.installed_apps import *
from taskite.settings.middleware import *
from taskite.settings.templates import *
from taskite.settings.databases import *
from taskite.settings.auth_password_validators import *
from taskite.settings.i18n import *
from taskite.settings.logging import *
from taskite.settings.cors import *

# Take environment variables from .env file
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG')

# ALLOWED_HOSTS = get_list_from_string(os.environ.get("ALLOWED_HOST", ""))
ALLOWED_HOSTS = env.list("ALLOWED_HOSTS", default=["*"])

ROOT_URLCONF = "taskite.urls"
WSGI_APPLICATION = "taskite.wsgi.application"

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "static"

MEDIA_ROOT = BASE_DIR / "media"
MEDIA_URL = "media/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
AUTH_USER_MODEL = "taskite.User"
LOGIN_URL = "/login"

DJANGO_VITE_DEV_MODE = DEBUG
DJANGO_VITE_MANIFEST_PATH = BASE_DIR / "static/dist/manifest.json"
DJANGO_VITE_STATIC_URL_PREFIX = "dist"

ORGANIZATION_SETTINGS = {
    "organization_name": "Acorn Globus",
    "primary_color": "#1677ff",
}

def immutable_file_test(path, url):
    # Match vite (rollup)-generated hashes, à la, `some_file-CSliV9zW.js`
    return re.match(r"^.+[.-][0-9a-zA-Z_-]{8,12}\..+$", url)
WHITENOISE_IMMUTABLE_FILE_TEST = immutable_file_test
