# Generated by Django 5.0.4 on 2024-04-12 10:27

from django.db import migrations, models


def generate_display_name_for_existing_users(apps, schema_editor):
    User = apps.get_model("taskite", "User")
    for user in User.objects.all():
        user.display_name = user.full_name.split()[0].lower()
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ("taskite", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="display_name",
            field=models.CharField(blank=True, max_length=125),
        ),
        migrations.RunPython(generate_display_name_for_existing_users, reverse_code=migrations.RunPython.noop)
    ]
