# Generated by Django 5.0.4 on 2024-04-12 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taskite", "0002_user_display_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="name",
            field=models.TextField(),
        ),
    ]
