# Generated by Django 5.0.4 on 2024-04-19 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taskite", "0002_alter_task_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="state",
            name="order",
            field=models.FloatField(blank=True, editable=False),
        ),
    ]
