# Generated by Django 5.0.4 on 2024-04-26 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taskite", "0003_alter_state_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="thumbnail",
            field=models.ImageField(
                blank=True, null=True, upload_to="projects/thumbnails/"
            ),
        ),
    ]
