# Generated by Django 5.0.4 on 2024-04-12 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taskite", "0003_alter_task_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="name",
            field=models.TextField(max_length=512),
        ),
    ]
