# Generated by Django 5.0.4 on 2024-04-12 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("taskite", "0004_alter_task_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="assginees",
            new_name="assignees",
        ),
    ]
