# Generated by Django 5.0.4 on 2024-04-30 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taskite", "0006_task_parent"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="next_task_sequence",
            field=models.IntegerField(default=1),
        ),
    ]
