# Generated by Django 5.0.4 on 2024-04-14 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taskite", "0007_alter_taskassignee_task"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="order",
            field=models.FloatField(blank=True, default=50000),
        ),
    ]
