# Generated by Django 5.0.4 on 2024-04-15 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taskite", "0008_alter_task_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="order",
            field=models.FloatField(blank=True, default=50000, editable=False),
        ),
    ]
