# Generated by Django 5.0.4 on 2024-05-05 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taskite", "0009_storage"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="projects/logos/"),
        ),
    ]
