# Generated by Django 5.0.4 on 2024-05-05 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("taskite", "0010_project_logo"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="thumbnail",
            new_name="cover",
        ),
    ]
