# Generated by Django 5.0.4 on 2024-05-06 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taskite", "0013_alter_user_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="cover",
            field=models.ImageField(
                blank=True, null=True, upload_to="media/projects/covers/"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="logo",
            field=models.ImageField(
                blank=True, null=True, upload_to="media/projects/logos/"
            ),
        ),
    ]
