# Generated by Django 5.0.4 on 2024-05-08 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("taskite", "0014_alter_project_cover_alter_project_logo"),
    ]

    operations = [
        migrations.RenameField(
            model_name="storage",
            old_name="uploaded_at",
            new_name="confirmed_at",
        ),
    ]
