# Generated by Django 5.0.4 on 2024-05-08 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taskite", "0015_rename_uploaded_at_storage_confirmed_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
