# Generated by Django 5.0.4 on 2024-05-08 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taskite", "0017_alter_user_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="timezone",
            field=models.CharField(default="UTC", max_length=100),
        ),
    ]
