# Generated by Django 5.0.4 on 2024-05-09 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taskite", "0018_user_timezone"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="logo",
        ),
        migrations.AlterField(
            model_name="project",
            name="cover",
            field=models.ImageField(blank=True, null=True, upload_to="media/admins/"),
        ),
    ]
