# Generated by Django 5.0.4 on 2024-05-09 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taskite", "0019_remove_project_logo_alter_project_cover"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to="media/admins/"),
        ),
    ]
