# Generated by Django 5.0.4 on 2024-05-09 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taskite", "0020_alter_user_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="archived_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
