# Generated by Django 5.0.4 on 2024-05-09 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taskite", "0021_project_archived_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="storage",
            name="bucket",
            field=models.CharField(blank=True, max_length=124, null=True),
        ),
    ]
