# Generated by Django 5.0.4 on 2024-05-14 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taskite", "0022_storage_bucket"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="storage",
            options={"ordering": ("-created_at",)},
        ),
        migrations.AddField(
            model_name="project",
            name="theme_color",
            field=models.CharField(default="#1677ff", max_length=10),
        ),
    ]
