# Generated by Django 5.0.4 on 2024-05-15 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("taskite", "0025_projectmember_accepted_at"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ProjectMemberInvite",
        ),
    ]
