# Generated by Django 5.0.4 on 2024-05-15 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("taskite", "0026_delete_projectmemberinvite"),
    ]

    operations = [
        migrations.RenameField(
            model_name="projectmember",
            old_name="accepted_at",
            new_name="joined_at",
        ),
    ]
