# Generated by Django 5.0.4 on 2024-05-21 06:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taskite", "0028_projectinvite"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projectmember",
            name="invited_at",
        ),
        migrations.AlterField(
            model_name="projectmember",
            name="joined_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
